
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: {{.namespace}}
  name: nginx-ingress-controller
  labels:
    k8s-app: nginx-ingress-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: nginx-ingress-controller
      annotations:
        prometheus.io/port: '10254'
        prometheus.io/scrape: 'true'
    spec:
      terminationGracePeriodSeconds: 60
      containers:
# Only create the datadog instance if we have a key defined          
{{ if .datadogapikey }}
      - image: datadog/docker-dd-agent:latest
        name: datadog
        env:
        - name: API_KEY
          value: {{.datadogapikey}}
        volumeMounts:
          - name: datadogconf
            mountPath: /conf.d/nginx.yaml
            subPath: nginx.yaml
{{ end }}
      - image: {{.ingressimage}}
        name: nginx-ingress-controller
        volumeMounts:
          - name: otherconf
            mountPath: /etc/nginx/other.conf
            subPath: other.conf
        readinessProbe:
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 1
        ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        args:
        - /nginx-ingress-controller
        - --default-backend-service=$(POD_NAMESPACE)/default-http-backend
        - --default-ssl-certificate=$(POD_NAMESPACE)/{{.tlssecretname}}
        - --configmap=$(POD_NAMESPACE)/nginxsettings
      volumes:
      - name: otherconf
        configMap:
          name: otherconf
      - name: datadogconf
        configMap:
          name: datadogconf
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  namespace: {{.namespace}}
spec:
  type: LoadBalancer
  externalTrafficPolicy: "Local"
  ports:
    - port: 80
      name: http
    - port: 443
      name: https
  selector:
    k8s-app: nginx-ingress-controller
---
