apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: nginx-ingress
spec:
  rules:
  - host: test.support.beamery.com
    http:
      paths:
      - backend:
          serviceName: web
          servicePort: 9090
