apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  namespace: {{.namespace}}
spec:
  type: LoadBalancer
  externalTrafficPolicy: "Local"
  ports:
    - port: 80
      name: http
    - port: 443
      name: https
  selector:
    k8s-app: nginx-ingress-controller
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{.namespace}}
  name: default-http-backend
  labels:
    k8s-app: default-http-backend
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    k8s-app: default-http-backend
