apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-ingress-controller
  namespace: {{.namespace}}

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nginx-ingress-controller-binding
subjects:
  - kind: ServiceAccount
    name: nginx-ingress-controller
    namespace: {{.namespace}}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
